<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20181126 15:18:51.899" generator="Robot 3.0.3 (Python 2.7.14 on darwin)">
<suite source="/Users/david/Desktop/Exercise_Web_Page_RF/robot/Tests/Functional/login_test.robot" id="s1" name="Login Test">
<test id="s1-t1" name="Headless Browser Correct Loggin">
<kw name="Start Virtual Display" library="XvfbRobot">
<doc>Starts virtual display which will be</doc>
<msg timestamp="20181126 15:18:52.080" level="TRACE">Arguments: [  ]</msg>
<msg timestamp="20181126 15:18:52.080" level="INFO">Using virtual display: '1440x900x24'</msg>
<msg timestamp="20181126 15:18:52.082" level="FAIL">EnvironmentError: Can not find Xvfb. Please install it and try again.</msg>
<msg timestamp="20181126 15:18:52.082" level="DEBUG">Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/XvfbRobot/__init__.py", line 56, in start_virtual_display
    int(colordepth), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)</msg>
<status status="FAIL" endtime="20181126 15:18:52.082" starttime="20181126 15:18:52.080"></status>
</kw>
<status status="FAIL" endtime="20181126 15:18:52.082" critical="yes" starttime="20181126 15:18:52.080">EnvironmentError: Can not find Xvfb. Please install it and try again.</status>
</test>
<status status="FAIL" endtime="20181126 15:18:52.083" starttime="20181126 15:18:51.902"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Login Test" pass="0">Login Test</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
